"""initial schema: employees, projects, seats, seat_allocations

Revision ID: 7ee664189008
Revises: 
Create Date: 2026-07-13 22:45:21.313818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee664189008'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('manager_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'ON_HOLD', 'COMPLETED')", name=op.f('ck_projects_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('bay', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE')", name=op.f('ck_seats_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('floor', 'zone', 'bay', 'seat_number', name=op.f('uq_seats_floor_zone_bay_seat_number'))
    )
    op.create_index('ix_seats_floor_zone', 'seats', ['floor', 'zone'], unique=False)
    op.create_index(op.f('ix_seats_seat_code'), 'seats', ['seat_code'], unique=False)
    op.create_index('ix_seats_status', 'seats', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'ON_LEAVE', 'EXITED', 'PENDING_ALLOCATION')", name=op.f('ck_employees_status_valid')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_employees_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('email', name=op.f('uq_employees_email')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_employees_employee_code'))
    )
    op.create_index('ix_employees_department', 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_project_id'), 'employees', ['project_id'], unique=False)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('allocation_status', sa.String(length=20), nullable=False),
    sa.Column('allocation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("allocation_status IN ('ACTIVE', 'RELEASED')", name=op.f('ck_seat_allocations_status_valid')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_seat_allocations_employee_id_employees')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_seat_allocations_project_id_projects')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_seat_allocations_seat_id_seats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_allocations'))
    )
    op.create_index(op.f('ix_seat_allocations_employee_id'), 'seat_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_seat_allocations_project_id'), 'seat_allocations', ['project_id'], unique=False)
    op.create_index(op.f('ix_seat_allocations_seat_id'), 'seat_allocations', ['seat_id'], unique=False)
    op.create_index('uq_seat_allocations_one_active_per_employee', 'seat_allocations', ['employee_id'], unique=True, sqlite_where=sa.text("allocation_status = 'ACTIVE'"), postgresql_where=sa.text("allocation_status = 'ACTIVE'"))
    op.create_index('uq_seat_allocations_one_active_per_seat', 'seat_allocations', ['seat_id'], unique=True, sqlite_where=sa.text("allocation_status = 'ACTIVE'"), postgresql_where=sa.text("allocation_status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_seat_allocations_one_active_per_seat', table_name='seat_allocations', sqlite_where=sa.text("allocation_status = 'ACTIVE'"), postgresql_where=sa.text("allocation_status = 'ACTIVE'"))
    op.drop_index('uq_seat_allocations_one_active_per_employee', table_name='seat_allocations', sqlite_where=sa.text("allocation_status = 'ACTIVE'"), postgresql_where=sa.text("allocation_status = 'ACTIVE'"))
    op.drop_index(op.f('ix_seat_allocations_seat_id'), table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_project_id'), table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_employee_id'), table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index(op.f('ix_employees_project_id'), table_name='employees')
    op.drop_index('ix_employees_department', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_seats_status', table_name='seats')
    op.drop_index(op.f('ix_seats_seat_code'), table_name='seats')
    op.drop_index('ix_seats_floor_zone', table_name='seats')
    op.drop_table('seats')
    op.drop_table('projects')
    # ### end Alembic commands ###
